version: '3'

services:
  reckue-postgres:
    container_name: reckue-postgres
    image: 'postgres:11.1'
    networks:
      - net
    ports:
      - 7060:5432
    environment:
      LC_ALL: 'C.UTF-8'
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: postgres
      POSTGRES_DB: reckue-keycloak
      PGDATA: /var/lib/postgresql/data
      restart: unless-stopped

  reckue-keycloak:
    container_name: reckue-keycloak
    image: jboss/keycloak:12.0.0
    networks:
      - net
    ports:
      - 7070:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: reckue-postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: reckue-keycloak
      DB_SCHEMA: public
    depends_on:
      - reckue-postgres
    restart: unless-stopped

networks:
  net:
    driver: bridge
